smart_factory:
  target: dev
  outputs:
    dev:
      type: postgres
      # TODO Sprint 3: kui compose.yml service `db` nimetatakse ümber `analytics-db`-ks,
      # tagasta host: "{{ env_var('POSTGRES_HOST', 'analytics-db') }}"
      host: db
      port: 5432
      user: "{{ env_var('POSTGRES_USER', 'praktikum') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'praktikum') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'praktikum') }}"
      schema: public
      threads: 2
