input:
  mqtt:
    urls: [ "tcp://192.168.99.119:1883" ]
    topics: [ "umh/v1/metalfab/eindhoven/+/+/_raw/#" ]
    client_id: rp_connect_ingestor

pipeline:
  processors:
    - mapping: |
        let topic_parts = metadata("mqtt_topic").split("/")
        root.value = this
        root.topic = @mqtt_topic
        root.timestamp = now()
        root.dept = $topic_parts.index(4)
        root.machine = $topic_parts.index(5)
        root.tag = $topic_parts.index(7)
        
output:
  file:
    path: '/data/lake/year=${! now().ts_strftime("%Y") }/month=${! now().ts_strftime("%m") }/day=${! now().ts_strftime("%d") }/dept=${! this.dept }/machine=${! this.machine }/tag=${! this.tag }/data-${!timestamp_unix() }-${!uuid_v4() }.json'
#  stdout: {}